### ISSUE TITLE
Does this allow .gitlab-ci.yml to specify caching?

### ISSUE THREAD

**Issue by NullVoxPopuli** [schmunk42/docker-gitlab-runner#3]
Right now my biggest problem with gitlab/docker-compose is that the images aren't cached between pipeline builds on the same branch (so even a small build takes about 5 minutes).

Here is my current gitlab ci file for reference:
```yml
image: tmaier/docker-compose:latest
cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - /var/lib/docker
    - node_modules/
    - bower_components/
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
before_script:
  - docker version
  - docker-compose version
  - docker-compose -f docker-compose.test.ci.yml build
  - docker-compose -f docker-compose.test.ci.yml run --rm test-server npm install
eslint:
  script:
    - docker-compose -f docker-compose.test.ci.yml run --rm test-server npm run eslint-no-fix
tests:
  script:
    - docker-compose -f docker-compose.test.ci.yml run --rm test-server
```

How would using `docker-gitlab-runner` be better?
